class UserBlockedError(Exception):
    pass


class UserNotFoundError(Exception):
    pass
